<html>
<head>
<title>TestNG:  Test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>7/2/2</td>
</tr><tr>
<td>Started on:</td><td>Mon Feb 03 20:47:47 IST 2025</td>
</tr>
<tr><td>Total time:</td><td>81 seconds (81729 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td><b>Attribute(s)</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='Ecommerce.tests.DataDrivenCheck.submitOrder()'><b>submitOrder</b><br>Test class: Ecommerce.tests.DataDrivenCheck<br>Parameters: {password=Iamking@000, product=IPHONE 13 PRO, email=anshika@gmail.com}</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at Ecommerce.tests.DataDrivenCheck.submitOrder(DataDrivenCheck.java:47)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace599316979", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace599316979'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertTrue(Assert.java:57)
	at org.testng.Assert.assertTrue(Assert.java:67)
	at Ecommerce.tests.DataDrivenCheck.submitOrder(DataDrivenCheck.java:47)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
	at org.testng.SuiteRunner.run(SuiteRunner.java:312)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
	at org.testng.TestNG.runSuites(TestNG.java:1112)
	at org.testng.TestNG.run(TestNG.java:1079)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
</pre></div></td>
<td>13</td>
<td>Ecommerce.tests.DataDrivenCheck@2362f559</td></tr>
<tr>
<td title='Ecommerce.tests.ErrorValidation.loginErrorValidation()'><b>loginErrorValidation</b><br>Test class: Ecommerce.tests.ErrorValidation</td>
<td><div><pre>java.lang.AssertionError: expected [Incorrect email or password.] but found [Icorrect email or password.]
	at Ecommerce.tests.ErrorValidation.loginErrorValidation(ErrorValidation.java:27)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace958209587", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace958209587'><pre>java.lang.AssertionError: expected [Incorrect email or password.] but found [Icorrect email or password.]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertEqualsImpl(Assert.java:150)
	at org.testng.Assert.assertEquals(Assert.java:132)
	at org.testng.Assert.assertEquals(Assert.java:656)
	at org.testng.Assert.assertEquals(Assert.java:666)
	at Ecommerce.tests.ErrorValidation.loginErrorValidation(ErrorValidation.java:27)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
	at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
	at org.testng.SuiteRunner.run(SuiteRunner.java:312)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
	at org.testng.TestNG.runSuites(TestNG.java:1112)
	at org.testng.TestNG.run(TestNG.java:1079)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
</pre></div></td>
<td>0</td>
<td>Ecommerce.tests.ErrorValidation@b2c9a9c</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td><b>Attribute(s)</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='Ecommerce.tests.DataDrivenCheck.submitOrder()'><b>submitOrder</b><br>Test class: Ecommerce.tests.DataDrivenCheck<br>Parameters: {password=Srita@sen25, product=QWERTY, email=srita.sen@gmail.com}</td>
<td></td>
<td>4</td>
<td>Ecommerce.tests.DataDrivenCheck@2362f559</td></tr>
<tr>
<td title='Ecommerce.tests.StandAloneTestRefracted.orderHistoryTest()'><b>orderHistoryTest</b><br>Test class: Ecommerce.tests.StandAloneTestRefracted</td>
<td></td>
<td>0</td>
<td>Ecommerce.tests.StandAloneTestRefracted@179ece50</td></tr>
<tr>
<td title='Ecommerce.tests.DataDrivenCheck.submitOrder()'><b>submitOrder</b><br>Test class: Ecommerce.tests.DataDrivenCheck<br>Parameters: {password=Iamking@000, product=IPHONE 13 PRO, email=shetty@gmail.com}</td>
<td></td>
<td>4</td>
<td>Ecommerce.tests.DataDrivenCheck@2362f559</td></tr>
<tr>
<td title='Ecommerce.tests.ErrorValidation.ProductErrorValidation()'><b>ProductErrorValidation</b><br>Test class: Ecommerce.tests.ErrorValidation<br>Parameters: {password=Iamking@000, product=IPHONE 13 PRO, email=anshika@gmail.com}</td>
<td></td>
<td>3</td>
<td>Ecommerce.tests.ErrorValidation@b2c9a9c</td></tr>
<tr>
<td title='Ecommerce.tests.ErrorValidation.ProductErrorValidation()'><b>ProductErrorValidation</b><br>Test class: Ecommerce.tests.ErrorValidation<br>Parameters: {password=Iamking@000, product=IPHONE 13 PRO, email=shetty@gmail.com}</td>
<td></td>
<td>3</td>
<td>Ecommerce.tests.ErrorValidation@b2c9a9c</td></tr>
<tr>
<td title='Ecommerce.tests.StandAloneTestRefracted.submitOrder()'><b>submitOrder</b><br>Test class: Ecommerce.tests.StandAloneTestRefracted</td>
<td></td>
<td>18</td>
<td>Ecommerce.tests.StandAloneTestRefracted@179ece50</td></tr>
<tr>
<td title='Ecommerce.tests.ErrorValidation.ProductErrorValidation()'><b>ProductErrorValidation</b><br>Test class: Ecommerce.tests.ErrorValidation<br>Parameters: {password=Srita@sen25, product=QWERTY, email=srita.sen@gmail.com}</td>
<td></td>
<td>3</td>
<td>Ecommerce.tests.ErrorValidation@b2c9a9c</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-skipped'>
<tr><td colspan='4' align='center'><b>SKIPPED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td><b>Attribute(s)</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='Ecommerce.tests.ErrorValidation.loginErrorValidation()'><b>loginErrorValidation</b><br>Test class: Ecommerce.tests.ErrorValidation</td>
<td><div><pre>java.lang.AssertionError: expected [Incorrect email or password.] but found [Icorrect email or password.]
	at Ecommerce.tests.ErrorValidation.loginErrorValidation(ErrorValidation.java:27)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace270261532", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace270261532'><pre>java.lang.AssertionError: expected [Incorrect email or password.] but found [Icorrect email or password.]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertEqualsImpl(Assert.java:150)
	at org.testng.Assert.assertEquals(Assert.java:132)
	at org.testng.Assert.assertEquals(Assert.java:656)
	at org.testng.Assert.assertEquals(Assert.java:666)
	at Ecommerce.tests.ErrorValidation.loginErrorValidation(ErrorValidation.java:27)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
	at org.testng.SuiteRunner.run(SuiteRunner.java:312)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
	at org.testng.TestNG.runSuites(TestNG.java:1112)
	at org.testng.TestNG.run(TestNG.java:1079)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
</pre></div></td>
<td>0</td>
<td>Ecommerce.tests.ErrorValidation@b2c9a9c</td></tr>
<tr>
<td title='Ecommerce.tests.DataDrivenCheck.orderHistoryTest()'><b>orderHistoryTest</b><br>Test class: Ecommerce.tests.DataDrivenCheck</td>
<td><div><pre>java.lang.Throwable: Method Ecommerce.tests.DataDrivenCheck.orderHistoryTest() on instance Ecommerce.tests.DataDrivenCheck@2362f559 depends on not successfully finished methods 
[Ecommerce.tests.DataDrivenCheck.submitOrder() on instance Ecommerce.tests.DataDrivenCheck@2362f559]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 18 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace166710672", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace166710672'><pre>java.lang.Throwable: Method Ecommerce.tests.DataDrivenCheck.orderHistoryTest() on instance Ecommerce.tests.DataDrivenCheck@2362f559 depends on not successfully finished methods 
[Ecommerce.tests.DataDrivenCheck.submitOrder() on instance Ecommerce.tests.DataDrivenCheck@2362f559]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
	at org.testng.SuiteRunner.run(SuiteRunner.java:312)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
	at org.testng.TestNG.runSuites(TestNG.java:1112)
	at org.testng.TestNG.run(TestNG.java:1079)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
</pre></div></td>
<td>0</td>
<td>Ecommerce.tests.DataDrivenCheck@2362f559</td></tr>
</table><p>
</body>
</html>